# If you are interested in seeing some real examples:

# => https://github.com/orta/ARAnalytics/blob/master/Bootstrap/Podfile
# => https://github.com/mneorr/ObjectiveSugar/blob/master/Example/Podfile
# or read the docs: http://docs.cocoapods.org/podfile.html

platform :ios

# Refer to the parent folder to grab the podspec locally
# this means we can edit it and changes will be made in that folder

def shared_pods
  pod "BBSimpleCocoapodsDevDependenciesLib", :path => "../Podspec"
end

# By default CocoaPods only makes changes to your main library
# so we ensure that the test library gets the pod by including it here.

# As it is included earlier with path CocoaPods will use the same version

target :BBSimpleCocoapodsDevDependencies do
  shared_pods
end

